version: "3.5"

services:
  desafio_anota_ai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "desafio_anota_ai"
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./:/app
    command: bash -c "npm install && npm run build && npm start"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456789

networks:
  default:
    name: local
