name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: List files
        run: ls -alh

      - name: Copy files via SSH
        run: |
          scp -o StrictHostKeyChecking=no -r ./ ec2-user@54.221.42.164:/home/ec2-user/projects/desafio-anota-ai

      - name: Install dependencies and restart app
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@54.221.42.164 << 'EOF'
          cd /home/ec2-user/projects/desafio-anota-ai
          npm install
          pm2 restart all ||  pm2 start dist/infra/main.js --name "main"
          exit
          EOF
